# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-09-05 22:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spelling_word', models.CharField(max_length=25)),
                ('grade_level', models.IntegerField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spell.Week')),
            ],
        ),
    ]
